version: "2"

run:
  timeout: 15m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
