name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Install dependencies
        run: make ci
      - name: Vulnerability Scan
        run: make vuln_scan

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Lint
        uses: golangci/golangci-lint-action@v6
