name: Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 13 * * 1"

permissions:
  contents: read

jobs:
  vuln-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Install dependencies
        run: make ci
      - name: Vulnerability Scan
        run: make vuln_scan
